### ISSUE TITLE
Resolve request page loading issue - invalid byte sequence in UTF-8 - iznos_bruto_mjesecnih_placa_nace_293

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#50]
### Actual behavior

```
An ArgumentError occurred in request#show:

invalid byte sequence in UTF-8
activesupport (3.2.21) lib/active_support/core_ext/object/blank.rb:105:in `=~'


-------------------------------
Request:
-------------------------------

* URL : http://imamopravoznati.org/request/iznos_bruto_mjesecnih_placa_nace_293
* IP address: [REDACTED]
* Parameters: {"controller"=>"request", "action"=>"show", "url_title"=>"iznos_bruto_mjesecnih_placa_nace_293"}
* Rails root: /var/www/imamopravoznati.org/alaveteli
* Timestamp : 2018-01-24 14:51:05 +0100

-------------------------------
Session:
-------------------------------

* session id: "[REDACTED]"
* data: {"session_id"=>"[REDACTED]", "locale"=>"hr"}

-------------------------------
Environment:
-------------------------------

* GATEWAY_INTERFACE : CGI/1.2
* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
* HTTP_CF_CONNECTING_IP : [REDACTED]
* HTTP_CF_IPCOUNTRY : BR
* HTTP_CF_RAY : [REDACTED]
* HTTP_CF_VISITOR : {"scheme":"http"}
* HTTP_CONNECTION : close
* HTTP_COOKIE : __cfduid=[REDACTED]
* HTTP_HOST : imamopravoznati.org
* HTTP_UPGRADE_INSECURE_REQUESTS : 1
* HTTP_USER_AGENT : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[REDACTED] Safari/537.36
* HTTP_VERSION : HTTP/1.0
* HTTP_X_ACCEL_MAPPING : /var/www/imamopravoznati.org/alaveteli/cache/zips/production/download=/download
* HTTP_X_FORWARDED_FOR : [REDACTED], [REDACTED]
* HTTP_X_FORWARDED_PROTO : http
* HTTP_X_REAL_IP : [REDACTED]
* HTTP_X_SENDFILE_TYPE : X-Accel-Redirect
* ORIGINAL_FULLPATH : /request/iznos_bruto_mjesecnih_placa_nace_293
* PATH_INFO : /request/iznos_bruto_mjesecnih_placa_nace_293
* QUERY_STRING : 
* REMOTE_ADDR : 127.0.0.1
* REQUEST_METHOD : GET
* REQUEST_PATH : /request/iznos_bruto_mjesecnih_placa_nace_293
* REQUEST_URI : /request/iznos_bruto_mjesecnih_placa_nace_293
* SCRIPT_NAME : 
* SERVER_NAME : imamopravoznati.org
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : thin 1.5.1 codename Straight Razor
* action_controller.instance : request#show
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x00000004bba090>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x00000013a8a698>
* action_dispatch.logger : #<ActiveSupport::TaggedLogging:0x00000004916b68>
* action_dispatch.parameter_filter : [:password, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/
, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST
_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RA
W_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/, /RAW_POST_DATA/]
* action_dispatch.remote_ip : [REDACTED]
* action_dispatch.request.content_type : 
* action_dispatch.request.flash_hash : #<ActionDispatch::Flash::FlashHash:0x000000139c2580>
* action_dispatch.request.formats : [text/html]
* action_dispatch.request.parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"iznos_bruto_mjesecnih_placa_nace_293"}
* action_dispatch.request.path_parameters : {:controller=>"request", :action=>"show", :url_title=>"iznos_bruto_mjesecnih_placa_nace_293"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {"session_id"=>"[REDACTED]"}
* action_dispatch.request_id : [REDACTED]
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x0000000494e680>
* action_dispatch.secret_token : [REDACTED]
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* async.callback : #<Method: Thin::Connection#post_process>
* async.close : #<EventMachine::DefaultDeferrable:0x00000013a95cc8>
* exception_notifier.options : {:sender_address=>"[REDACTED]", :exception_recipients=>["[REDACTED]"], :email_prefix=>"[ERROR] [imamopravoznati.org] ", :email_format=>:text, :sections=>["request", "session", "environment", "backtrace"], :background_sections=>["backtrace", "data"], :verbose_subject=>true, :normalize_subject=>false, :template_path=>"exception_notifier", :smtp_settings=>nil, :email_headers=>{}, :ignore_exceptions=>["ActiveRecord::RecordNotFound", "AbstractController::ActionNotFound", "ActionController::RoutingError"], :ignore_crawlers=>[], :ignore_if=>#<Proc:0x00000004a229a8@/home/alaveteli/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:37 (lambda)>}
* newrelic.transaction_started : true
* rack.errors : #<IO:0x00000001b16308>
* rack.input : #<StringIO:0x00000013a96d30>
* rack.multiprocess : false
* rack.multithread : false
* rack.request.cookie_hash : {"__cfduid"=>"[REDACTED]"}
* rack.request.cookie_string : __cfduid=[REDACTED]
* rack.request.query_hash : {}
* rack.request.query_string : 
* rack.run_once : false
* rack.session : {"session_id"=>"[REDACTED]", "locale"=>"hr"}
* rack.session.options : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"[REDACTED]", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000004a21a30>, :id=>"[REDACTED]"}
* rack.url_scheme : http
* rack.version : [1, 0]

* Process: 19339
* Server : imamopravoznati

-------------------------------
Backtrace:
-------------------------------

activesupport (3.2.21) lib/active_support/core_ext/object/blank.rb:105:in `=~'
activesupport (3.2.21) lib/active_support/core_ext/object/blank.rb:105:in `!~'
activesupport (3.2.21) lib/active_support/core_ext/object/blank.rb:105:in `blank?'
mail (2.5.4) lib/mail/body.rb:36:in `initialize'
mail (2.5.4) lib/mail/message.rb:2000:in `new'
mail (2.5.4) lib/mail/message.rb:2000:in `process_body_raw'
mail (2.5.4) lib/mail/message.rb:1234:in `body'
mail (2.5.4) lib/mail/message.rb:1593:in `parts'
mail (2.5.4) lib/mail/message.rb:1631:in `attachments'
mail (2.5.4) lib/mail/message.rb:1635:in `has_attachments?'
actionmailer (3.2.21) lib/action_mailer/base.rb:671:in `set_content_type'
actionmailer (3.2.21) lib/action_mailer/base.rb:652:in `mail'
exception_notification (3.0.1) lib/exception_notifier/notifier.rb:171:in `compose_email'
exception_notification (3.0.1) lib/exception_notifier/notifier.rb:100:in `exception_notification'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionmailer (3.2.21) lib/action_mailer/base.rb:459:in `process'
actionmailer (3.2.21) lib/action_mailer/base.rb:453:in `initialize'
actionmailer (3.2.21) lib/action_mailer/base.rb:439:in `new'
actionmailer (3.2.21) lib/action_mailer/base.rb:439:in `method_missing'
app/controllers/application_controller.rb:174:in `render_exception'
activesupport (3.2.21) lib/active_support/rescuable.rb:80:in `call'
activesupport (3.2.21) lib/active_support/rescuable.rb:80:in `rescue_with_handler'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/etag.rb:23:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.6) lib/rack/session/abstract/id.rb:205:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__3679339625351318505__call__2166477168078964082__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/methodoverride.rb:21:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/runtime.rb:17:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/lock.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack-utf8_sanitizer (1.3.0) lib/rack/utf8_sanitizer.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
thin (1.5.1) lib/thin/connection.rb:79:in `catch'
thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:54:in `process'
thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
thin (1.5.1) lib/thin/server.rb:159:in `start'
thin (1.5.1) lib/thin/controllers/controller.rb:86:in `start'
thin (1.5.1) lib/thin/runner.rb:187:in `run_command'
thin (1.5.1) lib/thin/runner.rb:152:in `run!'
thin (1.5.1) bin/thin:6:in `<top (required)>'
/home/alaveteli/bundle/ruby/1.9.1/bin/thin:19:in `load'
/home/alaveteli/bundle/ruby/1.9.1/bin/thin:19:in `<main>'
```

### Steps to reproduce

Go to URL : http://imamopravoznati.org/request/iznos_bruto_mjesecnih_placa_nace_293

**Comment by schlos** [comment]
Also for same request (admin URL): http://imamopravoznati.org/admin/requests/1926

**Comment by schlos** [comment]
Helpdesk: https://imamopravoznati.freshdesk.com/a/tickets/1220

**Comment by schlos** [comment]
Not reproducible with v0.33.0.0
