### ISSUE TITLE
Two bodies with the same historical URL name - turisticka_zajednica_ivanic_grad

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#52]
### Actual behavior

Subject: [ERROR] [imamopravoznati.org] public_body_change_requests#new (RuntimeError) "Two bodies with the same historical URL na...

Description:
```
A RuntimeError occurred in public_body_change_requests#new:

Two bodies with the same historical URL name: turisticka_zajednica_ivanic_grad
app/models/public_body.rb:218:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

* URL : http://imamopravoznati.org/change_request/new?body=turisticka_zajednica_ivanic_grad
* IP address: [REDACTED]
* Parameters: {"body"=>"turisticka_zajednica_ivanic_grad", "action"=>"new", "controller"=>"public_body_change_requests"}
* Rails root: /var/www/imamopravoznati.org/alaveteli
* Timestamp : 2018-01-20 00:23:10 +0100

-------------------------------
Session:
-------------------------------

[REDACTED]

-------------------------------
Environment:
-------------------------------

[REDACTED]

* Process: 16249
* Server : imamopravoznati

-------------------------------
Backtrace:
-------------------------------

app/models/public_body.rb:218:in `find_by_url_name_with_historic'
app/controllers/public_body_change_requests_controller.rb:12:in `new'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.21) lib/active_support/callbacks.rb:602:in `block in _run__3755725671467291758__process_action__3367838544144345657__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1289'
app/controllers/application_controller.rb:110:in `record_memory'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1289'
activesupport (3.2.21) lib/active_support/callbacks.rb:590:in `_run__3755725671467291758__process_action__3367838544144345657__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/etag.rb:23:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.6) lib/rack/session/abstract/id.rb:205:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__4580147800331426539__call__3855967279936261331__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/methodoverride.rb:21:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/runtime.rb:17:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack (1.4.6) lib/rack/lock.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
rack-utf8_sanitizer (1.3.0) lib/rack/utf8_sanitizer.rb:15:in `call'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
thin (1.5.1) lib/thin/connection.rb:79:in `catch'
thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:54:in `process'
thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
thin (1.5.1) lib/thin/server.rb:159:in `start'
thin (1.5.1) lib/thin/controllers/controller.rb:86:in `start'
thin (1.5.1) lib/thin/runner.rb:187:in `run_command'
thin (1.5.1) lib/thin/runner.rb:152:in `run!'
thin (1.5.1) bin/thin:6:in `<top (required)>'
/home/alaveteli/bundle/ruby/1.9.1/bin/thin:19:in `load'
/home/alaveteli/bundle/ruby/1.9.1/bin/thin:19:in `<main>'
```

**Comment by schlos** [comment]
Helpdesk: https://imamopravoznati.freshdesk.com/a/tickets/7251

**Comment by schlos** [comment]
Reproducible in v0.30.0.0 with:

```
A RuntimeError occurred in track#track_public_body:

  Two bodies with the same historical URL name: turisticka_zajednica_zminj
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/feed/body/turisticka_zajednica_zminj
```

```
A RuntimeError occurred in track#track_public_body:

  Two bodies with the same historical URL name: vodovod_i_odvodnja_senj
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/feed/body/vodovod_i_odvodnja_senj
```

```
A RuntimeError occurred in public_body#show:

  Two bodies with the same historical URL name: prekrsajni_sud_u_splitu
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/body/prekrsajni_sud_u_splitu
```

```
A RuntimeError occurred in request#new:

  Two bodies with the same historical URL name: turisticka_zajednica_vukovar
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/new/turisticka_zajednica_vukovar
```


```
A RuntimeError occurred in public_body_change_requests#new:

  Two bodies with the same historical URL name: turisticka_zajednica_knin
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/change_request/new?body=turisticka_zajednica_knin
```


```
A RuntimeError occurred in track#track_public_body:

  Two bodies with the same historical URL name: prekrsajni_sud_u_splitu
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/feed/body/prekrsajni_sud_u_splitu
```

```
A RuntimeError occurred in public_body_change_requests#new:

  Two bodies with the same historical URL name: turisticka_zajednica_knin
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/change_request/new?body=turisticka_zajednica_knin
```

```
A RuntimeError occurred in public_body#show:

  Two bodies with the same historical URL name: turisticka_zajednica_knin
  app/models/public_body.rb:218:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL       : http://imamopravoznati.org/body/turisticka_zajednica_knin
```

**Comment by schlos** [comment]
https://github.com/mysociety/alaveteli/issues/2489

**Comment by schlos** [comment]
Still reproducible with Alaveteli 0.33.0.0

**Comment by schlos** [comment]
```
A RuntimeError occurred in public_body#show:

  Two bodies with the same historical URL name: turisticka_zajednica_pakostane
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/body/turisticka_zajednica_pakostane
```

**Comment by schlos** [comment]
```
A RuntimeError occurred in public_body#show:

  Two bodies with the same historical URL name: visoko_uciliste_effectus_visoka_skola_za_financije_i_pravo_zagreb
  app/models/public_body.rb:273:in `find_by_url_name_with_historic'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/body/visoko_uciliste_effectus_visoka_skola_za_financije_i_pravo_zagreb
```

**Comment by schlos** [comment]
Still reproducible with Alaveteli 0.39.x.x

**Comment by garethrees** [comment]
This is a somewhat intentional error in that it's a data quality situation that needs action. You can see how we dealt with a recent issue on WDTK at https://github.com/mysociety/whatdotheyknow-theme/issues/879#issuecomment-907117765.

**Comment by schlos** [comment]
Thanks Gareth.
Just noting for myself comment with procedure: https://github.com/mysociety/whatdotheyknow-theme/issues/879#issuecomment-907123559
