### ISSUE TITLE
Error 500: [ERROR] admin_holiday_imports#create (ActiveModel::ForbiddenAttributesError) "ActiveModel::ForbiddenAttributesError"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#78]
### Actual behavior

```
An ActiveModel::ForbiddenAttributesError occurred in admin_holiday_imports#create:

  ActiveModel::ForbiddenAttributesError
  app/models/holiday_import.rb:50:in `block in holidays_attributes='


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/admin/holiday_imports

-------------------------------
Backtrace:
-------------------------------

  app/models/holiday_import.rb:50:in `block in holidays_attributes='
  app/models/holiday_import.rb:50:in `holidays_attributes='
  app/models/holiday_import.rb:29:in `initialize'
  app/controllers/admin_holiday_imports_controller.rb:10:in `new'
  app/controllers/admin_holiday_imports_controller.rb:10:in `create'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

Error in browser:

This page isn’t working imamopravoznati.org is currently unable to handle this request.
HTTP ERROR 500

### Version

http://imamopravoznati.org/version.json

* "alaveteli_version": "0.30.0.0",
* "ruby_version": "1.9.3",

### Steps to reproduce

1. http://imamopravoznati.org/admin/holidays
2. add Croatian holidays for 2020 - 2021

### Expected behavior

Should add holidays without error.

**Comment by schlos** [comment]
Fix pushed with https://github.com/mysociety/alaveteli/pull/4417 (0.30.0.2)

**Comment by schlos** [comment]
Needs retesting after version upgrade

**Comment by schlos** [comment]
Not reproducible with Alaveteli v0.33.0.0. Closing.
