### ISSUE TITLE
[ERROR] user#signin (ActionController::InvalidAuthenticityToken) "ActionController::InvalidAuthenticityToken"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#80]
### Actual behavior

```
An ActionController::InvalidAuthenticityToken occurred in user#signin:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/profile/sign_in

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

```
An ActionController::InvalidAuthenticityToken occurred in request#new:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/new

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

```
An ActionController::InvalidAuthenticityToken occurred in about_me#update:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/en/profile/about_me

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

### Version

http://imamopravoznati.org/version.json

* "alaveteli_version": "0.30.0.0",
* "ruby_version": "1.9.3",

**Comment by schlos** [comment]
Same as upstream issue: https://github.com/mysociety/alaveteli/issues/5435

UPDATE from garethrees:

> there a quite a few different places this happens; I'm not sure this particular issue is the same as yours, as this passes through handle_unverified_request. Doesn't look like that line is included in your backtrace.
> 
> I think #4484 is probably most relevant for you, which is an issue to collect all the different types of InvalidAuthenticityToken errors.

**Comment by schlos** [comment]
To be monitored for reproducibility on v0.33.0.0

**Comment by schlos** [comment]
Relevant upstream issue: https://github.com/mysociety/alaveteli/issues/4484

**Comment by schlos** [comment]
Last occurence:
Feb 22, 2021 at 11:08 AM (6 months ago)

https://imamopravoznati.pagerduty.com/incidents/PGYCAQC

**Comment by schlos** [comment]
Not reproducible in 0.39.0.0
To be reopened if gets reproduced again.
